# Generated by Django 5.0.2 on 2024-02-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reg',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
