# Generated by Django 5.0.2 on 2024-02-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishcart', '0003_rename_conformpasswords_reg_conformpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='fishpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('breed', models.CharField(max_length=30, null='True')),
                ('status', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='fish/')),
            ],
        ),
    ]
