# Generated by Django 5.0.2 on 2024-02-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishcart', '0004_fishpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='fish/')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
