# Generated by Django 4.2 on 2024-02-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishcart', '0005_addcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
